### ISSUE TITLE
Roadmap 2023

### ISSUE THREAD

**Issue by Damego** [Damego/ETIS-mobile#13]
Написанное приложение в 2022 году является цельным куском говнокода. Поэтому есть смысл написать дорожную карту на 2023 год, чтобы улучшить данное приложение.

## Главные изменения

- [ ] Полный перевод приложения на TypeScript
- [ ] Использование Redux для рендера компонентов.
- [ ] Переписать методы парсера.

## Стили
- [ ] Поддержка тёмной темы

P.S. Данный список будет пополняться вплоть до конца января 2023 года.
